version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/apache/Dockerfile
    ports:
      - "${APP_PORT:-8080}:80"
    volumes:
      - ./app:/var/www/html
    command: sh -c "composer install --no-dev --optimize-autoloader && apache2-foreground"
    depends_on:
        - db
    env_file:
      - .env
  db:
    image: mysql:5.7
    container_name: mysql-ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT:-3307}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env

volumes:
  mysql_data:
